### PR TITLE
Validate genetic association object properties

### PR DESCRIPTION
**Pull request by fedde-s**
The json-schema definition for the fields specific to the
genetic_association data type contained some lines that looked like they
were nested at the wrong level to be recognised as definitions of the
shape of the object's fields.

### CODE REVIEW

**Comment by fedde-s** [comment]
Does this make sense? I haven't tested it, but it looked like the `variant:` and `evidence:` fields should be in the list of properties for a `genetic_association` object rather than on the same level as the words `properties:` and `required:`.

**Comment by fedde-s** [comment]
I think the effect would be that properties specific to `genetic_association` objects were previously accepted without any validation, but will now be validated.

**Comment by fedde-s** [comment]
Some of the field specifications that will now be parsed were invalid according to the JSON Schema format. I added two commits to fix those, making the check on Travis CI happy again.

**Comment by AsierGonzalez** [comment]
Hi @fedde-s,
Did you validate any files with the new schema version? All the `genetic_association` files now fail the validation with a `is not valid under any of the given schemas` error and we are unable to find what the issue is.

**Comment by fedde-s** [comment]
As I said above, no, I hadn't tested it. But the way I read it, `genetic_association` files were previously accepted without any validation whatsoever, so I imagine that discrepancies between the designed schema and the data files we have been using may have gone undetected in the previous releases.

**Comment by AsierGonzalez** [comment]
Absolutely, what you say makes sense and the change was needed to make sure that `genetic_association` evidence are validated. It's just that we don't know how it's possible that all the evidence files are invalid. We suspect that this must have been the case since the different json schemas where merged into one file in version 1.4.0.
I'll open a ticket and I'll investigate further.

**Comment by fedde-s** [comment]
Since it concerns all of the files, I do think it's almost certainly the schema that should be adjusted to match the data rather than vice versa, unless that change is clearly in contrast to what the schema was designed to do.

**Comment by AsierGonzalez** [comment]
Most likely, we just need to find the reason for not been valid in the first place. The output of the validator is not too helpful and, unfortunatley, @afaulconbridge is away at the moment.

**Pull request merged**
