### PR TITLE
Add enum for ClinVar review status

### PR DESCRIPTION
**Pull request by tskir**
Since we have one for clinical significance and even for modes of inheritance, it seems like a good idea to add this one as well

### CODE REVIEW

**Review by AsierGonzalez — APPROVED** [review]

**Comment by tskir** [comment]
I have now added validation for the `clinvar_rating` to the `somatic_mutation`'s `evidence` section as well, using definitions to avoid duplication.

Also, to avoid having to resolve multiple conflicts, I have rebased this PR on top of #95, so it now contains all changes from that one as well.

**Comment by AsierGonzalez** [comment]
Sounds good, can I then close #95 without merging it?

**Comment by tskir** [comment]
@AsierGonzalez Yes, absolutely. In fact, if you merge this PR, #95 will close automatically, as GitHub can see that #96 is built on top of #95 and includes all changes from it as well.

Also, going even further, all of my four PRs are built on top of each other: #95 → #96 → #97 → #99. So, for example, if you review and merge #99, all others will automatically close.

**Comment by AsierGonzalez** [comment]
That's good to know. I'll look into all of them and if everything's fine I'll merge #99, that makes it easier.

**Pull request merged**
